version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "8888:8888" # Health Check extension
    depends_on:
      - tempo

  # Tempo (Distributed Tracing Backend)
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "14268:14268" # Jaeger Thrift HTTP
      - "3200:3200"   # Tempo HTTP (for Grafana)
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--timeout=1", "http://localhost:3200/ready"]
      interval: 5s
      timeout: 1s
      retries: 10

  # Grafana for Visualization
  grafana:
    image: grafana/grafana:10.4.2 # Use a recent stable version
    container_name: grafana
    restart: always
    ports:
      - "3000:3000" # Grafana UI
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - tempo # Grafana needs Tempo to be up

volumes:
  db_data:
  tempo_data:
  grafana_data:
