server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 5_000_000
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 720h # Example value, can be adjusted

query_frontend:
  search:
    enabled: true
    attribute_index:
      attributes:
        - key: globalId
          type: string
      backend: embedded
      embedded:
        path: /tmp/tempo/attribute-index

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

usage_stats:
  enabled: false
