spring:
  application:
    name: spring-boot-server

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    name: logs/app.log
  pattern:
    # Include traceId/spanId/globalId in both console and file logs
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [trace_id=%X{traceId} span_id=%X{spanId} globalId=%X{globalId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [trace_id=%X{traceId} span_id=%X{spanId} globalId=%X{globalId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.example.demo: DEBUG
    org.springframework.web: INFO
    # Hibernate 6 (Spring Boot 3.x): SQL과 바인딩 값 로깅
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

management:
  observations:
    annotations:
      enabled: true # Spring Boot 3.5에서는 관찰 애노테이션 스캐닝이 기본 비활성화
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
        fields: globalId # The MDC key
      remote-fields: globalId
      local-fields: globalId
      tag-fields: globalId
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: "*"
