receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp/tempo:
    endpoint: tempo:4317 # Tempo's OTLP gRPC endpoint
    tls:
      insecure: true
  debug:
    verbosity: detailed

# TODO : check extensions
#extensions:
#  health_check:
#    endpoint: 0.0.0.0:13133
#  pprof:
#    endpoint: 0.0.0.0:1777
#  zpages:
#    endpoint: 0.0.0.0:55679

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/tempo]